title: DaF-Unterricht Stufe 4 Studienkolleg Mittelhessen
description: Unterrichtsmaterial für die Stufe 4 mit CodiMD Präsentationen
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
